### ISSUE TITLE
Cannot build the engine 

### ISSUE THREAD

**Issue by bazhenovc** [scriptum/Cheetah#5]
Hello.

I`ve tried to build the engine, but failed.
OS: Gentoo GNU/Linux
Arch: x86_64
Command: ./make_all.sh
Log: https://gist.github.com/4505347

**Comment by scriptum** [comment]
Seems that you dont have libSDL (x86 version) installed. Try **./make.sh native release**

Also make_all.sh will cross-compile for all supported platforms (Linux native, Linux 32, Win32) so you can use only **./make.sh native release**

I didn't write manual for the new build system yet.

**Comment by bazhenovc** [comment]
Ok, will try this evening

**Comment by bazhenovc** [comment]
Works fine now
